version: 2
jobs:
  foxy:
    docker:
      - image: ros:foxy-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt update -qq && apt install -y python3-argcomplete python3-colcon-common-extensions
            source `find /opt/ros -maxdepth 2 -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
      - run:
          name: Build
          command: |
            source `find /opt/ros -maxdepth 2 -name setup.bash | sort | head -1`
            cd ..
            colcon build --parallel-workers 4 --cmake-args -DCMAKE_BUILD_TYPE=Release
      - run:
          name: Run Tests
          command: |
            source `find /opt/ros -maxdepth 2 -name setup.bash | sort | head -1`
            cd ..
            colcon test
            colcon test-result
    working_directory: ~/src
    environment:
      - MAKEFLAGS: -j4

workflows:
  version: 2
  ros_build:
    jobs:
      - foxy
