name: Basic Build Workflow

on:
  - pull_request
  - push

jobs:
  build-dashing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: rostooling/setup-ros-docker:ubuntu-bionic-ros-dashing-ros-base-latest
    steps:
    - name: Fix Bugs in ros-tooling/action-ros-ci
      run: sudo chown -R rosbuild:rosbuild "$HOME" .
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.0.17
      with:
        package-name: |
          velodyne
          velodyne_driver
          velodyne_laserscan
          velodyne_msgs
          velodyne_pointcloud
        source-ros-binary-installation: dashing
        vcs-repo-file-url: ""
    - name: Upload logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()
